// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: syncer/proto/syncer.proto

package proto

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetBlocksRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetBlocksRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetBlocksRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetBlocksRequestMultiError, or nil if none found.
func (m *GetBlocksRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetBlocksRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for From

	if len(errors) > 0 {
		return GetBlocksRequestMultiError(errors)
	}

	return nil
}

// GetBlocksRequestMultiError is an error wrapping multiple validation errors
// returned by GetBlocksRequest.ValidateAll() if the designated constraints
// aren't met.
type GetBlocksRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetBlocksRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetBlocksRequestMultiError) AllErrors() []error { return m }

// GetBlocksRequestValidationError is the validation error returned by
// GetBlocksRequest.Validate if the designated constraints aren't met.
type GetBlocksRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetBlocksRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetBlocksRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetBlocksRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetBlocksRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetBlocksRequestValidationError) ErrorName() string { return "GetBlocksRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetBlocksRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetBlocksRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetBlocksRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetBlocksRequestValidationError{}

// Validate checks the field values on GetBlockByHashRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetBlockByHashRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetBlockByHashRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetBlockByHashRequestMultiError, or nil if none found.
func (m *GetBlockByHashRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetBlockByHashRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Hash

	if len(errors) > 0 {
		return GetBlockByHashRequestMultiError(errors)
	}

	return nil
}

// GetBlockByHashRequestMultiError is an error wrapping multiple validation
// errors returned by GetBlockByHashRequest.ValidateAll() if the designated
// constraints aren't met.
type GetBlockByHashRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetBlockByHashRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetBlockByHashRequestMultiError) AllErrors() []error { return m }

// GetBlockByHashRequestValidationError is the validation error returned by
// GetBlockByHashRequest.Validate if the designated constraints aren't met.
type GetBlockByHashRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetBlockByHashRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetBlockByHashRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetBlockByHashRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetBlockByHashRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetBlockByHashRequestValidationError) ErrorName() string {
	return "GetBlockByHashRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetBlockByHashRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetBlockByHashRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetBlockByHashRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetBlockByHashRequestValidationError{}

// Validate checks the field values on Block with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Block) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Block with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in BlockMultiError, or nil if none found.
func (m *Block) ValidateAll() error {
	return m.validate(true)
}

func (m *Block) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Block

	if len(errors) > 0 {
		return BlockMultiError(errors)
	}

	return nil
}

// BlockMultiError is an error wrapping multiple validation errors returned by
// Block.ValidateAll() if the designated constraints aren't met.
type BlockMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BlockMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BlockMultiError) AllErrors() []error { return m }

// BlockValidationError is the validation error returned by Block.Validate if
// the designated constraints aren't met.
type BlockValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BlockValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BlockValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BlockValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BlockValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BlockValidationError) ErrorName() string { return "BlockValidationError" }

// Error satisfies the builtin error interface
func (e BlockValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBlock.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BlockValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BlockValidationError{}

// Validate checks the field values on SyncPeerStatus with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SyncPeerStatus) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SyncPeerStatus with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SyncPeerStatusMultiError,
// or nil if none found.
func (m *SyncPeerStatus) ValidateAll() error {
	return m.validate(true)
}

func (m *SyncPeerStatus) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Number

	if len(errors) > 0 {
		return SyncPeerStatusMultiError(errors)
	}

	return nil
}

// SyncPeerStatusMultiError is an error wrapping multiple validation errors
// returned by SyncPeerStatus.ValidateAll() if the designated constraints
// aren't met.
type SyncPeerStatusMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SyncPeerStatusMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SyncPeerStatusMultiError) AllErrors() []error { return m }

// SyncPeerStatusValidationError is the validation error returned by
// SyncPeerStatus.Validate if the designated constraints aren't met.
type SyncPeerStatusValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SyncPeerStatusValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SyncPeerStatusValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SyncPeerStatusValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SyncPeerStatusValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SyncPeerStatusValidationError) ErrorName() string { return "SyncPeerStatusValidationError" }

// Error satisfies the builtin error interface
func (e SyncPeerStatusValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSyncPeerStatus.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SyncPeerStatusValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SyncPeerStatusValidationError{}
