// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.0
// 	protoc        v4.25.3
// source: consensus/dpos/proto/signature.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 签名请求消息
type SignatureRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockNumber    uint64 `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	BlockHash      []byte `protobuf:"bytes,2,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	CheckpointHash []byte `protobuf:"bytes,3,opt,name=checkpoint_hash,json=checkpointHash,proto3" json:"checkpoint_hash,omitempty"`
	Round          uint64 `protobuf:"varint,4,opt,name=round,proto3" json:"round,omitempty"`
	Proposer       []byte `protobuf:"bytes,5,opt,name=proposer,proto3" json:"proposer,omitempty"`
	Timestamp      uint64 `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *SignatureRequest) Reset() {
	*x = SignatureRequest{}
}

func (x *SignatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignatureRequest) ProtoMessage() {}

func (x *SignatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_dpos_proto_signature_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SignatureRequest) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *SignatureRequest) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *SignatureRequest) GetCheckpointHash() []byte {
	if x != nil {
		return x.CheckpointHash
	}
	return nil
}

func (x *SignatureRequest) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *SignatureRequest) GetProposer() []byte {
	if x != nil {
		return x.Proposer
	}
	return nil
}

func (x *SignatureRequest) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 签名响应消息
type SignatureResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ValidatorAddr  []byte `protobuf:"bytes,1,opt,name=validator_addr,json=validatorAddr,proto3" json:"validator_addr,omitempty"`
	Signature      []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	CheckpointHash []byte `protobuf:"bytes,3,opt,name=checkpoint_hash,json=checkpointHash,proto3" json:"checkpoint_hash,omitempty"`
	Timestamp      uint64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *SignatureResponse) Reset() {
	*x = SignatureResponse{}
}

func (x *SignatureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignatureResponse) ProtoMessage() {}

func (x *SignatureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_dpos_proto_signature_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SignatureResponse) GetValidatorAddr() []byte {
	if x != nil {
		return x.ValidatorAddr
	}
	return nil
}

func (x *SignatureResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignatureResponse) GetCheckpointHash() []byte {
	if x != nil {
		return x.CheckpointHash
	}
	return nil
}

func (x *SignatureResponse) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_consensus_dpos_proto_signature_proto protoreflect.FileDescriptor

var file_consensus_dpos_proto_signature_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_consensus_dpos_proto_signature_proto_goTypes = []interface{}{
	(*SignatureRequest)(nil),  // 0: v1.SignatureRequest
	(*SignatureResponse)(nil), // 1: v1.SignatureResponse
}

// func init() { file_consensus_dpos_proto_signature_proto_init() }
// func file_consensus_dpos_proto_signature_proto_init() {
// 	if File_consensus_dpos_proto_signature_proto != nil {
// 		return
// 	}
// 	
// 	// 初始化MessageInfo数组
// 	file_consensus_dpos_proto_signature_proto_msgTypes[0] = protoimpl.MessageInfo{
// 		Exporter: func(v interface{}, i int) interface{} {
// 			switch v := v.(*SignatureRequest); i {
// 			case 0:
// 				return &v.state
// 			case 1:
// 				return &v.sizeCache
// 			case 2:
// 				return &v.unknownFields
// 			default:
// 				return nil
// 			}
// 		},
// 	}
// 	
// 	file_consensus_dpos_proto_signature_proto_msgTypes[1] = protoimpl.MessageInfo{
// 		Exporter: func(v interface{}, i int) interface{} {
// 			switch v := v.(*SignatureResponse); i {
// 			case 0:
// 				return &v.state
// 			case 1:
// 				return &v.sizeCache
// 			case 2:
// 				return &v.unknownFields
// 			default:
// 				return nil
// 			}
// 		},
// 	}
// 	
// 	// 创建一个简单的文件描述符
// 	File_consensus_dpos_proto_signature_proto = &protoreflect.FileDescriptor{
// 		Syntax:  protoreflect.Proto3,
// 		Package: "v1",
// 	}
// }
