// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0--rc1
// source: consensus/dpos/proto/signature.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 签名请求消息
type SignatureRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BlockNumber    uint64                 `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	BlockHash      []byte                 `protobuf:"bytes,2,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	CheckpointHash []byte                 `protobuf:"bytes,3,opt,name=checkpoint_hash,json=checkpointHash,proto3" json:"checkpoint_hash,omitempty"`
	Round          uint64                 `protobuf:"varint,4,opt,name=round,proto3" json:"round,omitempty"`
	Proposer       []byte                 `protobuf:"bytes,5,opt,name=proposer,proto3" json:"proposer,omitempty"`
	Timestamp      uint64                 `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SignatureRequest) Reset() {
	*x = SignatureRequest{}
	mi := &file_consensus_dpos_proto_signature_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignatureRequest) ProtoMessage() {}

func (x *SignatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_dpos_proto_signature_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignatureRequest.ProtoReflect.Descriptor instead.
func (*SignatureRequest) Descriptor() ([]byte, []int) {
	return file_consensus_dpos_proto_signature_proto_rawDescGZIP(), []int{0}
}

func (x *SignatureRequest) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *SignatureRequest) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *SignatureRequest) GetCheckpointHash() []byte {
	if x != nil {
		return x.CheckpointHash
	}
	return nil
}

func (x *SignatureRequest) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *SignatureRequest) GetProposer() []byte {
	if x != nil {
		return x.Proposer
	}
	return nil
}

func (x *SignatureRequest) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 签名响应消息
type SignatureResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ValidatorAddr  []byte                 `protobuf:"bytes,1,opt,name=validator_addr,json=validatorAddr,proto3" json:"validator_addr,omitempty"`
	Signature      []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	CheckpointHash []byte                 `protobuf:"bytes,3,opt,name=checkpoint_hash,json=checkpointHash,proto3" json:"checkpoint_hash,omitempty"`
	Timestamp      uint64                 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SignatureResponse) Reset() {
	*x = SignatureResponse{}
	mi := &file_consensus_dpos_proto_signature_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignatureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignatureResponse) ProtoMessage() {}

func (x *SignatureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_dpos_proto_signature_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignatureResponse.ProtoReflect.Descriptor instead.
func (*SignatureResponse) Descriptor() ([]byte, []int) {
	return file_consensus_dpos_proto_signature_proto_rawDescGZIP(), []int{1}
}

func (x *SignatureResponse) GetValidatorAddr() []byte {
	if x != nil {
		return x.ValidatorAddr
	}
	return nil
}

func (x *SignatureResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignatureResponse) GetCheckpointHash() []byte {
	if x != nil {
		return x.CheckpointHash
	}
	return nil
}

func (x *SignatureResponse) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_consensus_dpos_proto_signature_proto protoreflect.FileDescriptor

const file_consensus_dpos_proto_signature_proto_rawDesc = "" +
	"\n" +
	"$consensus/dpos/proto/signature.proto\x12\x05proto\"\xcd\x01\n" +
	"\x10SignatureRequest\x12!\n" +
	"\fblock_number\x18\x01 \x01(\x04R\vblockNumber\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x02 \x01(\fR\tblockHash\x12'\n" +
	"\x0fcheckpoint_hash\x18\x03 \x01(\fR\x0echeckpointHash\x12\x14\n" +
	"\x05round\x18\x04 \x01(\x04R\x05round\x12\x1a\n" +
	"\bproposer\x18\x05 \x01(\fR\bproposer\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x04R\ttimestamp\"\x9f\x01\n" +
	"\x11SignatureResponse\x12%\n" +
	"\x0evalidator_addr\x18\x01 \x01(\fR\rvalidatorAddr\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12'\n" +
	"\x0fcheckpoint_hash\x18\x03 \x01(\fR\x0echeckpointHash\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x04R\ttimestampB7Z5github.com/Vcity-Team/vcitychain/consensus/dpos/protob\x06proto3"

var (
	file_consensus_dpos_proto_signature_proto_rawDescOnce sync.Once
	file_consensus_dpos_proto_signature_proto_rawDescData []byte
)

func file_consensus_dpos_proto_signature_proto_rawDescGZIP() []byte {
	file_consensus_dpos_proto_signature_proto_rawDescOnce.Do(func() {
		file_consensus_dpos_proto_signature_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_consensus_dpos_proto_signature_proto_rawDesc), len(file_consensus_dpos_proto_signature_proto_rawDesc)))
	})
	return file_consensus_dpos_proto_signature_proto_rawDescData
}

var file_consensus_dpos_proto_signature_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_consensus_dpos_proto_signature_proto_goTypes = []any{
	(*SignatureRequest)(nil),  // 0: proto.SignatureRequest
	(*SignatureResponse)(nil), // 1: proto.SignatureResponse
}
var file_consensus_dpos_proto_signature_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_consensus_dpos_proto_signature_proto_init() }
func file_consensus_dpos_proto_signature_proto_init() {
	if File_consensus_dpos_proto_signature_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_consensus_dpos_proto_signature_proto_rawDesc), len(file_consensus_dpos_proto_signature_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_consensus_dpos_proto_signature_proto_goTypes,
		DependencyIndexes: file_consensus_dpos_proto_signature_proto_depIdxs,
		MessageInfos:      file_consensus_dpos_proto_signature_proto_msgTypes,
	}.Build()
	File_consensus_dpos_proto_signature_proto = out.File
	file_consensus_dpos_proto_signature_proto_goTypes = nil
	file_consensus_dpos_proto_signature_proto_depIdxs = nil
}
